### ISSUE TITLE
⚙️ Setting Project Up ⚙️

### ISSUE THREAD

**Issue by damla** [damla/sinestezi#3]
# To-Dos

- [x] Delete workspace of code sandbox.
- [x] Clean readme part.
- [x] Delete unused components from project.
